# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 12_hana

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'npm install -g mbt @sap/cds-dk'
  displayName: Install CAP Build tools and CAP runtime env

- script: mbt build -p=cf -s=$(Agent.BuildDirectory)/s/
  displayName: MTA build

- script: test -d $(Agent.BuildDirectory)/s/app1/mta_archives || exit 1
  displayName: Validate archive build

- script: |
    wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
    echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  displayName: Add the Cloud Foundry Foundation public key and package repository to our system

- script: |
    sudo apt-get update
    sudo apt-get install cf8-cli
  displayName: Install Clound Foundry CLI

- script: cf install-plugin multiapps -f
  displayName: Install Cloud runtime dependency

- script: cf login -a $(cf.api) -u $(cf.login) -p $(cf.passwd) -o $(cf.orgnm) -s $(cf.space)
  displayName: Login into CF space

- script: cf deploy $(Agent.BuildDirectory)/s/app1/mta_archives/app1_1.0.0.mtar
  displayName: Deploy to CF space

